### ISSUE TITLE
Failed to resolve: com.github.BoardiesITSolutions:Android-MySQL-Connector:0.31_MYSQL8

### ISSUE THREAD

**Issue by sanketshahane05** [BoardiesITSolutions/Android-MySQL-Connector#12]
**My app level gradle script is** 
apply plugin: 'com.android.application'

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.2"
    defaultConfig {
        applicationId "com.example.test"
        minSdkVersion 21
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation 'com.github.BoardiesITSolutions:Android-MySQL-Connector:0.31_MYSQL8'
}

my project level gradle script is

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.3'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

While adding dependencies
**ERROR: Failed to resolve: com.github.BoardiesITSolutions:Android-MySQL-Connector:0.31_MYSQL8**
Show in Project Structure dialog
Affected Modules: app

**Comment by boardy** [comment]
Hi,

Its due to the tag name being case sensitive, should be MySQL8 e.g.

`implementation 'com.github.BoardiesITSolutions:Android-MySQL-Connector:0.31_MySQL8'`

Notice the lower case 'y'. 

Thanks

Chris

**Comment by sanketshahane05** [comment]
Thank you silly mistake though i was not aware of that.

**Comment by boardy** [comment]
No worries, glad to help. I'll close this off but let me know if you run into any trouble. 

Chris
