### ISSUE TITLE
java.lang.IndexOutOfBoundsException when result is empty

### ISSUE THREAD

**Issue by cuplesoft** [BoardiesITSolutions/Android-MySQL-Connector#14]
Hi,

My MySQL version is 10.4.7-MariaDB and i using latest version 0.36_MySQL8.
If SELECT statement expect one or more records - everything is ok, but if result is empty then i have exception as below:

`Caused by: java.lang.IndexOutOfBoundsException at com.BoardiesITSolutions.AndroidMySQLConnector.MySQLIO.shiftCurrentBytePosition(MySQLIO.java:317) at com.BoardiesITSolutions.AndroidMySQLConnector.MySQLIO.getLenEncodedInt(MySQLIO.java:388) at com.BoardiesITSolutions.AndroidMySQLConnector.PacketManager.COM_QueryResponse.processPacketData(COM_QueryResponse.java:177) at com.BoardiesITSolutions.AndroidMySQLConnector.PacketManager.COM_QueryResponse.<init>(COM_QueryResponse.java:28) at com.BoardiesITSolutions.AndroidMySQLConnector.Statement$2.socketDataSent(Statement.java:227) at com.BoardiesITSolutions.AndroidMySQLConnector.SocketSender.doInBackground(SocketSender.java:56) at com.BoardiesITSolutions.AndroidMySQLConnector.SocketSender.doInBackground(SocketSender.java:12)`

**Comment by boardy** [comment]
Thanks, I'll look into this and let you know when there's a new version available.

Thanks
Chris

**Comment by boardy** [comment]
Hi cuplesoft, 

I've pushed 0.37_MySQL8 which fixes the problem with the empty result set. 

Let me know how you get on. 

Thanks 
Chris
