### ISSUE TITLE
Column type of mediumblob appears as BLOG in resultSet.fields

### ISSUE THREAD

**Issue by daniel-stoneuk** [BoardiesITSolutions/Android-MySQL-Connector#18]
Database: 
![image](https://user-images.githubusercontent.com/15860949/89440473-91602780-d743-11ea-8816-220920ef098b.png)

I'm trying to get the byte array for an image in a row but getBlob won't work, and the resultSet.fields shows that the column is picked up as BLOG. What data type is this?

**Comment by boardy** [comment]
I think BLOG is a typo there is no datatype called that.

When you try and get the blob data kit what happens is an exception thrown?

**Comment by daniel-stoneuk** [comment]
Ah that makes sense. Thanks for the quick reply.

Yeah, since a String can't be cast to a Byte array. The class MySQLRow stores data in a HashMap<ColumnDefinition, String>, then returns `return (byte[])entry.getValue();` which throws an exception. 

A workaround may be to getString and then call .toByteArray (kotlin), or .getBytes() Java, though I'm yet to check if this works.

**Comment by boardy** [comment]
Ok thanks. I'll check that out. There was a fix done for blobs a few months
ago so not sure what's happened there.

Leave it with me and I'll see if I can spot what's going.

**Comment by daniel-stoneuk** [comment]
Brilliant, thanks again so much for your help with this. 

In case this is any use - the following commit doesn't look like it was pulled up to the version 8 support branch https://github.com/BoardiesITSolutions/Android-MySQL-Connector/commit/3ae038aac283ea51be363a5bd313948220bb7a99

**Comment by boardy** [comment]
No problem. Glad to help :). I think it was just the MySQLRow class had the issue and the ColumnDefinition, I don't know how the MySQLRow class got reverted but that's why the recent fix I did to the BLOB broke when you tried to use it. 

I've tested again and looks to be working OK now. 

I've pushed 0_43_MySQL8 which fixes the BLOB issue and changes the data type to be BLOB instead of BLOG. While looking into this I also found an issue if the BLOB column just contained a plain string instead of binary data you would get cast error so that is also resolved now as well. 

Let me know how you get on.

Thanks

Chris

**Comment by daniel-stoneuk** [comment]
Fantastic, that seems to have fixed things. Thanks for sorting this. 

Just need to figure out how I can get this byte array to show in an ImageView now!

**Comment by daniel-stoneuk** [comment]
Btw, the data is mediumblob in the database 

![image](https://user-images.githubusercontent.com/15860949/89523108-40e7d900-d7da-11ea-8ac2-5bbe49e1610d.png)

but it's appearing as a BLOB (and not MEDIUM_BLOB) in the library 

![image](https://user-images.githubusercontent.com/15860949/89523148-4f35f500-d7da-11ea-96ba-2fee59f04e6b.png)

Should I ignore this or could this be why I'm not able to create a bitmap from it?

**Comment by boardy** [comment]
Strange. I'll look into that. I don't believe it should be causing an issue
in terms of functionality in the library, it's just an internal reference
for the column.

Thanks

Chris

**Comment by daniel-stoneuk** [comment]
Thanks! I'll mark this as closed now as the typo has been fixed. Cheers.

**Comment by boardy** [comment]
I've taken a look at MEDIUMBLOB column being shown as a BLOB, unfortunately there's no way for to fix that. The code is there to ensure that it chooses the right column type but looking at the MySQL packet response it returns a BLOB regardless if the column type is MEDIUM_BLOB. 

Not sure if the server changes this depending on the length of the actual data, e.g. if the column type is MEDIUMBLOB but the length of the data is within the size of a BLOB maybe the server returns BLOB regardless. 

Thanks
Chris
