### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by ani1nonly** [BoardiesITSolutions/Android-MySQL-Connector#20]
Query is not returning all data, there are more then 900 rows in table but some time return 130 or 150 or 670 randomly with the same query

**Comment by boardy** [comment]
Just to double check, are you using the 0.45_MySQL8 tag. If you are using one of main releases (without the MySQL8 on the end) it would like have issues. 

If so, can you let me know which version of MySQL/MariaDB you are using. 

Thanks
Chris

**Comment by ani1nonly** [comment]
Checked and found 0.45_MySQL8 in gradle implementation, 

Other info is as below

DATABASE SERVER
Server: 148.72.232.175 via TCP/IP 

Server type: Percona Server 

Server version: 5.5.51-38.1-log - Percona Server (GPL), Release rel30.2, Revision 39.1 

Protocol version: 10 Server charset: UTF-8 Unicode (utf8) 

Web server is as below
Apache/2.4.18 (Ubuntu) 

Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $ 

PHP extension: mysqli￼ mbstring￼ 

PHP version: 7.0.33-0ubuntu0.16.04.3


Storage Engine is MyISAM

**Comment by ani1nonly** [comment]
I m hosting my Database at Godaddy hosting site

**Comment by boardy** [comment]
Percona server doesn't look too be a true MySQL server from what I can tell
on Google.

The library only supports true MySQL servers or MariaDB

Thanks
Chris

**Comment by ani1nonly** [comment]
Also for note same query is working fine with jdbc connector. But your work is awesome and very fast in comparison with jdbc. Thanks for your effort :pray:

**Comment by boardy** [comment]
If it works with a JDBC driver then I guess mi e should work.

I'll see if I can install percona server and see what my library doesn't
like. I'll let you know how I get on and whether I'll be able to support it.

Thanks

Chris

**Comment by boardy** [comment]
I've taken a look at this and found that Percona 5.5 has been end of life since December 2018. 

I've installed Percona 5.7 with 1500 rows and all rows were returned as expected so I'd recommend upgrading percona server to the latest release. 

Thanks

Chris
