### ISSUE TITLE
Changing hostname taking long time to respond

### ISSUE THREAD

**Issue by vipafattal** [BoardiesITSolutions/Android-MySQL-Connector#21]
**Describe the bug**
When constructing a `Connection` with a hostname that is not existed on the server, `IConnectionInterface` takes too long till (around 6 mins) it sends an event exception containing a message that says "java.net.ConnectException: Failed to connect to /192.168.3.19 (port 3309) from /:: (port 39268): connect failed: ETIMEDOUT (Connection timed out)", after that when setting a hostname that does exist on the server it hangs till the connection of non-existed hostname on the server.

*To Reproduce**

Simply create a `Connection` object with a hostname that does not exist on the server, it hangs for some time till throwing "Connection timed out".

**Desktop (please complete the following information):**
 - Android Version: 8.1
 - MySQL Server Version: 5.1

**Comment by boardy** [comment]
Hey, thanks for reporting the issue. I've identified the cause so working on a fix so hopefully will get a new version out in the next day or so. I'll let you know when its ready. 

Thanks
Chris

**Comment by SofiaEngvall** [comment]
Thank you! My phone works just fine today. I read it was a global issue with a bad update of an app.Have a nice day!/SofiaSent from my Galaxy
-------- Original message --------From: Chris Board ***@***.***> Date: 3/23/21  22:59  (GMT+01:00) To: BoardiesITSolutions/Android-MySQL-Connector ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [BoardiesITSolutions/Android-MySQL-Connector] Changing hostname taking long time to respond (#21) 
Hey, thanks for reporting the issue. I've identified the cause so working on a fix so hopefully will get a new version out in the next day or so. I'll let you know when its ready.
Thanks
Chris

**Comment by boardy** [comment]
Hi. I believe there was an update done by Google with Web View which caused a fair number of Android apps to go wrong until google pushed another update. 

You did highlight an issue though as there is an issue where it does take too long to timeout and there's no ability to override the default, so I'll still push a new update that will change the default to 30 seconds, but also provide an ability to override the timeout so it can be extended/reduced as per a users requirement. 

Thanks
Chris

**Comment by boardy** [comment]
Hi, I've pushed tag 0.48_MySQL8 that fixes the high connection socket timeout and allows for it to be overridden if you need a shorter/or longer time than the new default (default is 30 seconds).

**Comment by SofiaEngvall** [comment]
Thanks :)Sent from my Galaxy
-------- Original message --------From: Chris Board ***@***.***> Date: 3/24/21  12:33  (GMT+01:00) To: BoardiesITSolutions/Android-MySQL-Connector ***@***.***> Cc: Sofia Engvall ***@***.***>, Comment ***@***.***> Subject: Re: [BoardiesITSolutions/Android-MySQL-Connector] Changing hostname taking long time to respond (#21) 
Hi. I believe there was an update done by Google with Web View which caused a fair number of Android apps to go wrong until google pushed another update.
You did highlight an issue though as there is an issue where it does take too long to timeout and there's no ability to override the default, so I'll still push a new update that will change the default to 30 seconds, but also provide an ability to override the timeout so it can be extended/reduced as per a users requirement.
Thanks
Chris

**Comment by vipafattal** [comment]
> Hi, I've pushed tag 0.48_MySQL8 that fixes the high connection socket timeout and allows for it to be overridden if you need a shorter/or longer time than the new default (default is 30 seconds).

Amazing!, thanks @boardy for this valuable update, I've just tested it, and worked as intended.
