### ISSUE TITLE
Add support for MySQL Server Language 5.5.0

### ISSUE THREAD

**Issue by numbereddev** [BoardiesITSolutions/Android-MySQL-Connector#23]
**Is your feature request related to a problem? Please describe.**
Support for MySQL Server Lanaguage 5.5.0

**Describe the solution you'd like**
Just add support for MySQL Server Language 5.5.0

**Describe alternatives you've considered**
Nothing

**Additional context**
Nothing

**Comment by boardy** [comment]
Hi, 
Sorry but I'm not  likely going be adding support for 5.5.x or below as this has been marked end of life by Oracle in December 2018 so is not recommended to continue using, so would therefore recommend to upgrade MySQL to at least 5.7.x

Thanks
Chris
