### ISSUE TITLE
Doesn't support compression and Attribute application Manifest

### ISSUE THREAD

**Issue by Agnaldo-MR** [BoardiesITSolutions/Android-MySQL-Connector#25]
Hello.
I saw in the API introduction that doesn't support compression, if the MySQL server reports that it supports compression, the connector will turn it off.

In handleMySQLConnException is returning message: Invalid zstd compression level for algorithm 'zstd'. I believe it is for this reason.

Do you have a prediction if it will be possible, someday, to solve this problem? I work with a company database where I cannot change the settings because it is a large company and serves many stores simultaneously. I need the API for small accesses and specific data return. And this API is perfect for my need. Unfortunately I am not able to use it. I even want to congratulate you for your availability and ability to implement this API.

Two other problems:

Attribute application@icon value=(@mipmap/ic_logomarca) from AndroidManifest.xml:32:9-47
is also present at [com.github.BoardiesITSolutions:Android-MySQL-Connector:0.48_MySQL8] AndroidManifest.xml:13:9-43 value=(@mipmap/ic_launcher).
Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:27:5-73:19 to override.

Attribute application@roundIcon value=(@mipmap/ic_logomarca_round) from AndroidManifest.xml:33:9-58
is also present at [com.github.BoardiesITSolutions:Android-MySQL-Connector:0.48_MySQL8] AndroidManifest.xml:15:9-54 value=(@mipmap/ic_launcher_round).
Suggestion: add 'tools:replace="android:roundIcon"' to <application> element at AndroidManifest.xml:27:5-73:19 to override.

Sorry for the english. I'm using the translator as I don't speak English.

![Compression](https://user-images.githubusercontent.com/62654732/196690260-f3c25ec3-24f1-43e8-98fc-430ac252a9b5.jpg)

![Android](https://user-images.githubusercontent.com/62654732/196690252-218098c7-2818-40d6-a024-557af006c0ac.jpg)

![Version](https://user-images.githubusercontent.com/62654732/196690267-0cbe866d-2a91-40e6-a0d4-a4d28bf6f79a.jpg)

**Comment by Agnaldo-MR** [comment]
For the last two problems I managed to solve like this: tools:replace="icon, roundIcon"

Other info: I have read-only access to mysql.

**Comment by boardy** [comment]
Hi, Apologise for the late response, I'm not sure how/why but I never saw the notification message from GitHub. 

I've not worked on the project in some time, so I can only assume, something changed within MySQL server that might mean the library isn't detecting the compression correctly to disable the flag. 

I'll set up a MySQL 8.0.22 server and see if I can replicate the problem and provide a fix.

**Comment by boardy** [comment]
Hi,

Unfortunately I don't have any good news. I replicated the issue with the zstd not being supported. I figured out the issue that even though the is a compression enabled flag, which was being turned off by the library, but there is an additional flag that specifies the compression zstd algorithm being enabled, this appears to override the client compression enabled flag. 

I updated the code and successfully connected to the database but then when fetching the data it goes wrong. 

Unfortunately it doesn't go wrong in any way that actually helps me try and debug what's going on. Although I get a successful connection, and I the same flags are sent to the database to turn features on or off as required match a working database, on MySQL 8.0.26 it returns a MySQL Malformed Packet in response to the query, although the data it sends appears to be the same. 

Unfortunately I'm not entirely sure whether I can progress this as I can't see anything that is failing. I've found there was a case of MariaDB upgrading and causing a similar issue for other client libraries such as PDO in PHP, but unfortunately I couldn't find anything non related to PHP and the PDO libraries. 

Thanks
Chris

**Comment by Agnaldo-MR** [comment]
I had a similar problem with mysql and I solved it this way: 
String hostURL = "jdbc:mysql://xx.xxx.xx.xxx:xxxx/-db-?characterEncoding=utf8";
(adding: ?characterEncoding=utf8";)
Using mysql-connector-java-5.1.4.jar.
Maybe it will help you. Thank you for your effort and I hope you find a solution.

Thanks.
Agnaldo

**Comment by boardy** [comment]
Hi Agnaldo,

Good news this time. I've figured out what the issue is I believe. A flags default seems to have been changed between older versions of MySQL and newer versions, and because of that flag it meant the server was expecting a slightly different query packet to what I was sending. 

I am going to do a bit more testing and make sure there's no other gotchas with other query types but all being well hopefully I'll get a release tonight or over the weekend. 

Thanks
Chris

**Comment by boardy** [comment]
Hi Agnaldo, 

New tag has been created which has resolved the issues. Tag name is 0.49_MySQL8. Let me know how you get on. 

Thanks
Chris

**Comment by Agnaldo-MR** [comment]
Hello. I want to thank you, because it worked perfectly. I did all the connection tests and queries without any errors. Thank you very much for your attention and availability.

**Comment by boardy** [comment]
That's great to hear. Thanks for confirming Agnaldo.
