### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: Handshake failed

### ISSUE THREAD

**Issue by alexju555** [BoardiesITSolutions/Android-MySQL-Connector#5]
Hi,

Trying to connect to Amazon aws mysql server with one database created. I run my app in a real device. 
I can connect from my pc using mysql command line in the same LAN network, connected to the same router.
I can connect using a Mysql client I have downloaded from Play Store to my cell (same cell I am using to run my App).
I cannot connect from my app and log reflects the following:

01/06 21:22:01: Launching app
$ adb shell am start -n "com.example.alexju.myapplication/com.example.alexju.myapplication.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Client not ready yet..Waiting for process to come online
Waiting for process to come online
Connected to process 22742 on device samsung-sm_j530f-5200c6704609452b
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
D/ViewRootImpl@e52d1c6[MainActivity]: ViewPostIme pointer 0
D/ViewRootImpl@e52d1c6[MainActivity]: ViewPostIme pointer 1
D/MySQLIO: Resetting Socket: Don't Expect Response: false
    Reading Socket Data
    Created baos
D/MySQLIO: Read from socket. Bytes Read: 82
    BAOS written: Bytes Written: 82
    Breaking from loop
    Loop compleeted
    Full data written to: now size: 82
D/Connection: Sending SSL Request
D/Connection: Packet Sequence Number Returned: 1
D/MySQLIO: Resetting Socket: Don't Expect Response: true
D/Connection: Socket Data Sent
D/Connection: Performing SSL Handshake
E/MySQLConnection: javax.net.ssl.SSLHandshakeException: Handshake failed

Code is as follows (I just have removed url partially, username, and password, I hope it is no needed here). But those should be right, because it works from computer and telephone.
Debugging code, it is is not passing though any of the (@Override)  functions inside Connection mysqlConnection.

package com.example.alexju.myapplication;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;
import android.widget.Toast;
import com.BoardiesITSolutions.AndroidMySQLConnector.*;
import com.BoardiesITSolutions.AndroidMySQLConnector.Exceptions.*;

import java.io.IOException;

public class MainActivity extends AppCompatActivity {

    Button button;
    TextView textView;
    String cadena;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Button button = findViewById(R.id.button);
        final TextView textView = findViewById(R.id.textView2);

        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {

                //Coneción a BD
                Connection mysqlConnection = new Connection("rds-mysql-10mintutorial.---.us-east-1.rds.amazonaws.com", "---",
                        "---", 3306, "prueba1", new IConnectionInterface()
                {
                    @Override
                    public void actionCompleted()
                    {
                        //You are now connected to the database
                        //Toast.makeText(getBaseContext(), "Conectado", Toast.LENGTH_SHORT).show();
                        cadena = "conectado!!";
                        //Mostrar dato leido
                        textView.setText(cadena);
                    }

                    @Override
                    public void handleInvalidSQLPacketException(InvalidSQLPacketException e)
                    {
                        //Handle the error
                        cadena = "error!!";
                        //Mostrar dato leido
                        textView.setText(cadena);
                        //Toast.makeText(getBaseContext(), "handleInvalidSQLPacketException", Toast.LENGTH_SHORT).show();
                    }

                    @Override
                    public void handleMySQLException(MySQLException e)
                    {
                        //Handle the error
                        cadena = "error!!";
                        //Mostrar dato leido
                        textView.setText(cadena);
                        //Toast.makeText(getBaseContext(), "handleMySQLException", Toast.LENGTH_SHORT).show();
                    }

                    @Override
                    public void handleIOException(IOException e)
                    {
                        //Handle the error
                        cadena = "error!!";
                        //Mostrar dato leido
                        textView.setText(cadena);
                        //Toast.makeText(getBaseContext(), "handleIOException", Toast.LENGTH_SHORT).show();
                    }

                    @Override
                    public void handleMySQLConnException(MySQLConnException e)
                    {
                        //Handle the error
                        cadena = "error!!";
                        //Mostrar dato leido
                        textView.setText(cadena);
                        //Toast.makeText(getBaseContext(), "handleMySQLConnException", Toast.LENGTH_SHORT).show();
                    }

                    @Override
                    public void handleException(Exception e)
                    {
                        //Handle the error
                        cadena = "error";
                        //Mostrar dato leido
                        textView.setText(cadena);
                        //Toast.makeText(getBaseContext(), "handleException", Toast.LENGTH_SHORT).show();
                    }
                });
                mysqlConnection.returnCallbackToMainThread(true, MainActivity.this);

                //Lectura Dato
                //cadena = "titi";
                //Mostrar dato leido
                //textView.setText(cadena);

            }
        });

**Comment by boardy** [comment]
Hi Alex, 

It might be a compatibility issue between the MySQL Connector and the MySQL server. I know very little about Amazon AWS, is this a specific Amazon AWS version of MySQL, or is it just a normal MySQL server you've installed on an Amazon server?

If it is Amazon specific, would you be able to send me a link on how to set up an Amazon MySQL instance so I can try and replicate the problem you're having, or if you've installed a standard MySQL server on a normal Amazon server can you let me know which MySQL server version you're using and I'll install it and see if I can replicate the problem. 

Thanks

Chris

**Comment by alexju555** [comment]
Hi Chris, 

It should be a regular server.
https://aws.amazon.com/getting-started/tutorials/create-mysql-db/

You have to create an account and it is free, but you have to write one credit card,  to sign up.
Then, just it easy to follow the tutorial.

If I could have your email, I could send connection information and you can try to check whether you get the same error or nor running your code. Or I can give you access to the server. My email is alexju555@gmail.com

On the other hand, I am in Spain and the server is in US, I have doubts on SSL certificate:
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ConnectToInstance.html#USER_ConnectToInstanceSSL.CLI

**Comment by boardy** [comment]
Hi Alex,

Don't worry about giving me access to your server, I'd likely need to do LAN traces and/or play with the config options to see what the problem is. 

I've got an Amazon account so it shouldn't be a problem to set up a server to replicate the problem. If connecting to the MySQL DB with the SSL parameter is a requirement for Amazon then the connect won't work as this isn't yet supported - if you don't need this you can disable the custom certificate requirement. MySQL can still connect securely as the library will send a MySQL welcome packet and MySQL will respond with what it supports, so if the TLS flag is set, the library then sends an SSL handshake request. 

When you connect to the DB via the command line do you need to specify the ssl-ca parameter for it to connect, if you can connect via the command line without this flag then technically the library should be able to connect, if the ssl-ca parameter is required though the library doesn't support this currently. If the ssl-ca parameter isnn't needed and you can connect via the command line but not the library it might be that Amazon installs MySQL with slightly different settings than the default MySQL install so that might be what's causing the problem. 

Can you let me know what MySQL version you selected and any other MySQL specific settings that Amazon asks and I'll set up a server and see if I can replicate the problem?

I start back at work tomorrow so will only have the evenings and weekends to take a look but I'll figure out the problem to this as soon as I can. 

Thanks

Chris

**Comment by alexju555** [comment]
Hi Chris, 

I am afraid I do not know how to disable the custom certificate requirement. Sorry.

I choose MySQL 5.6.40. I perfectly followed below tutorial, I did not change anything:
https://aws.amazon.com/getting-started/tutorials/create-mysql-db/

This is the way I connect by command line:
![image](https://user-images.githubusercontent.com/24739566/50742783-e6f2ec00-120f-11e9-9b58-b02249dbdad2.png)

Parameters:
![image](https://user-images.githubusercontent.com/24739566/50742972-49e58280-1212-11e9-84b4-444b06c646c9.png)


If you know other free MySQL server where I can tests, I can use, no problem for me.

**Comment by boardy** [comment]
Hi Alex, 

That's no problem, it doesn't look like you are using the ssl-ca parameter in your command line connection so I'm guessing Amazon installs MySQL with maybe slightly different config options which is causing the issue with the library. 

I'll set up an Amazon server and see if I can replicate the problem, I don't know of any other cloud provides giving free access unfortunately, other than installing a virtualisation platform on your PC such as Vmware or Dropbox and install a VM but I'll look into this Amazon issue and let you know. 

Thanks

Chris

**Comment by boardy** [comment]
Hi Alex, 

I've replicated your problem with the Amazon server, I'm not 100% sure yet how I'm going to figure the problem as assumed the amazon instance was a normal Linux box was MySQL pre-installed but it doesn't appear to be so can't perform a network trace from the DB itself to see what packets are being sent/received but I'll figure some way of testing it and get back to you as soon as possible. 

Thanks

Chris

**Comment by alexju555** [comment]
Hi Chris, 

Thats good news, at least it is replicated!
I have found another MySQL server which looks free. I will keep you informed as well.

Thanks a lot for your support.

**Comment by boardy** [comment]
Hi Alex, 

I've figured out the problem you'e been having. Unfortunately MySQL 5.6 only supports TLS 1.0 which is an old deprecated version of TLS which I don't believe Java and/or Android supports anymore. 

I've given an Amazon RDS instance running 5.7.16 a try to make sure and this support TLS 1.1 by default so the library can successfully connect to it, so I'd recommend upgrading your DB instance to be version 5.7.

Thanks

Chris

**Comment by alexju555** [comment]
Hi Chris, 

I could not select 5.7.16 as it was not available. But I have set 5.7.22 and it worked. Terrific!
Thank you a lot again. Great support.

**Comment by boardy** [comment]
That's great to hear, thanks for letting me know, glad to help.
